2022-02-03 12:21:37,496 ERROR: Exception on / [GET] [in C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\harit\Desktop\microBlog_Allweb\app\routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\harit\Desktop\microBlog_Allweb\app\templates\index.html", line 34, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-02-03 12:21:41,563 ERROR: Exception on /index [GET] [in C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\harit\Desktop\microBlog_Allweb\app\routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\harit\Desktop\microBlog_Allweb\app\templates\index.html", line 34, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-02-03 12:23:10,397 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:50]
2022-02-03 12:24:06,679 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:50]
2022-02-03 13:05:03,366 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:52]
2022-02-03 13:05:05,638 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:52]
2022-02-03 13:07:25,871 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:52]
2022-02-03 15:47:47,216 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:52]
2022-02-04 10:17:31,979 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:55]
2022-02-04 11:51:31,563 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:58]
2022-02-04 11:51:33,028 ERROR: Exception on / [GET] [in C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\utils.py", line 271, in decorated_view
    return current_app.login_manager.unauthorized()
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\login_manager.py", line 174, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\harit\Desktop\microBlog_Allweb\venv\lib\site-packages\werkzeug\routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2022-02-04 11:52:52,318 INFO: Microblog startup [in C:\Users\harit\Desktop\microBlog_Allweb\app\__init__.py:58]
